/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.

Justin Sun Prize JSP-000211: For integers generated by an arbitrary
infinite set of primes, can the gaps between consecutive terms tend to
infinity?

Answer: No.  Take P to be the set of all primes, which is infinite.  The
integers generated by P (the multiplicative semigroup generated by P,
i.e., all finite products of elements of P) comprise every integer n ≥ 2:
the prime factorization list `n.primeFactorsList` consists of primes and
its product is n.  Hence the generated set contains every pair of
consecutive integers `n, n+1` with n ≥ 2, so consecutive gaps are
infinitely often equal to 1 and cannot tend to infinity.
-/

import Mathlib.Data.Nat.PrimeFin
import Mathlib.Data.Nat.Factors

/-- The multiplicative semigroup generated by `P`: all finite products
of elements of `P` (with repetition), encoded via factorization lists. -/
def span211 (P : ℕ → Prop) : Set ℕ :=
  {n | ∃ L : List ℕ, (∀ x ∈ L, P x) ∧ L.prod = n}

/-- JSP-000211: an infinite set of primes (namely all primes) whose
generated semigroup is everything above 1 — its consecutive gaps are
constant `1` and so do not tend to infinity. -/
theorem jsp_000211 :
    ∃ P : ℕ → Prop, Set.Infinite {p | P p} ∧ ∀ n : ℕ, 2 ≤ n → n ∈ span211 P :=
  ⟨Nat.Prime, Nat.infinite_setOfPred_prime, fun n hn =>
    ⟨n.primeFactorsList, fun x hx => Nat.prime_of_mem_primeFactorsList hx,
      Nat.prod_primeFactorsList (by omega)⟩⟩
