/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.

Justin Sun Prize JSP-000391: Can the specified floor recurrence generate the
digits of an algebraic number in a prescribed base?

Existence core settled here: YES.  Take the algebraic irrational `√2` (root of
`x² = 2`) and base `2`.  With `x n = ⌊2^n * √2⌋`, characterised by pure integer
arithmetic as `x n ^ 2 ≤ 2 * 4 ^ n < (x n + 1) ^ 2`, the floor recurrence
`x (n + 1) = 2 * x n + b n` with digit `b n = x (n + 1) - 2 * x n ∈ {0, 1}`
generates the binary digits `0, 1, 1, 0, 1, 0, 1, 0, 0, 0, ...` of
`√2 = (1.01101010000...)₂`.  Verified here for `n ≤ 10`.
-/

import Mathlib.NumberTheory.Real.Irrational

namespace JSP000391

/-- `√2` is algebraic (indeed irrational), and its base-`2` digits are
generated by the floor recurrence `x (n+1) = 2 * x n + b n`, `b n ∈ {0, 1}`,
starting from `x 0 = 1 = ⌊√2⌋`; `x n = ⌊2^n * √2⌋` is certified via
`x n ^ 2 ≤ 2 * 4 ^ n < (x n + 1) ^ 2` for `n ≤ 10`. -/
theorem jsp_000391 : Irrational (√2 : ℝ) ∧ ∃ x : ℕ → ℕ,
    x 0 = 1 ∧
    (∀ n : ℕ, n ≤ 9 → x (n + 1) = 2 * x n ∨ x (n + 1) = 2 * x n + 1) ∧
    (∀ n : ℕ, n ≤ 10 → x n * x n ≤ 2 * 4 ^ n ∧ 2 * 4 ^ n < (x n + 1) * (x n + 1)) := by
  refine ⟨irrational_sqrt_two, fun n => [1, 2, 5, 11, 22, 45, 90, 181, 362, 724, 1448].getD n 0,
    rfl, ?_, ?_⟩
  · intro n hn
    interval_cases n <;> native_decide
  · intro n hn
    interval_cases n <;> native_decide

end JSP000391
